import { ArrowUpRight, Globe2, Mail, ShieldCheck } from "lucide-react";
import { useNavigate } from "react-router-dom";

export default function Footer() {
  const navigate = useNavigate();
  return <footer className="bg-slate-950 px-5 pb-7 pt-16 text-slate-300 sm:px-8 sm:pt-20"><div className="mx-auto max-w-7xl"><div className="grid gap-12 border-b border-white/10 pb-12 lg:grid-cols-[1.35fr_.65fr_.65fr_.8fr]"><div><button onClick={() => navigate("/")} className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-white text-slate-950"><ShieldCheck size={20} /></span><span className="text-xl font-bold tracking-tight text-white">SENTRYNX</span></button><p className="mt-5 max-w-sm text-sm leading-6 text-slate-400">Clear domain security intelligence for every decision that starts with a click.</p><div className="mt-6 flex gap-3"><FooterIcon icon={Globe2} label="Website" /><FooterIcon icon={Mail} label="Email" /></div></div><FooterLinks title="Product" links={[["Scan a domain", "/"], ["Saved reports", "/history"], ["How it works", "/about"]]} navigate={navigate} /><FooterLinks title="Platform" links={[["Threat intelligence", "/about"], ["Email security", "/about"], ["Domain trust", "/about"]]} navigate={navigate} /><div><p className="text-sm font-bold text-white">Scan with confidence</p><p className="mt-3 text-sm leading-6 text-slate-400">Get a clear security verdict before you trust a new website.</p><button onClick={() => navigate("/")} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-sm font-bold text-slate-950 transition hover:bg-cyan-100">Start a scan <ArrowUpRight size={16} /></button></div></div><div className="flex flex-col gap-3 pt-7 text-xs text-slate-500 sm:flex-row sm:items-center sm:justify-between"><p>© {new Date().getFullYear()} Sentrynx. Domain intelligence, made clear.</p><div className="flex gap-5"><span>Built for safer decisions</span><span>Privacy-first scanning</span></div></div></div></footer>;
}

function FooterIcon({ icon: Icon, label }) { return <a href="#" aria-label={label} className="flex h-9 w-9 items-center justify-center rounded-lg border border-white/10 text-slate-400 transition hover:border-cyan-300/50 hover:bg-cyan-300/10 hover:text-cyan-200"><Icon size={16} /></a>; }
function FooterLinks({ title, links, navigate }) { return <div><p className="text-sm font-bold text-white">{title}</p><div className="mt-4 space-y-3">{links.map(([label, to]) => <button key={label} onClick={() => navigate(to)} className="block text-sm text-slate-400 transition hover:text-cyan-200">{label}</button>)}</div></div>; }
