import { useState } from "react";
import { AlertTriangle, CheckCircle2, ChevronRight, Clipboard, FileSearch, Link2, LoaderCircle, MailCheck, ShieldAlert, ShieldCheck } from "lucide-react";
import MainLayout from "../layout/MainLayout";

const API_URL = import.meta.env.VITE_API_URL;
const demoEmail = `From: Microsoft Security <security@micros0ft-alert.example>
Reply-To: verify@account-review.example
Subject: Urgent: unusual activity requires verification
Authentication-Results: mx.example; spf=fail smtp.mailfrom=micros0ft-alert.example; dkim=fail; dmarc=fail

Your account has been suspended. Verify immediately at https://micros0ft-alert.example/login?verify=1`;
const severity = { high: "border-rose-400/30 bg-rose-400/10 text-rose-100", medium: "border-amber-300/30 bg-amber-300/10 text-amber-100", low: "border-emerald-300/20 bg-emerald-300/10 text-emerald-100" };

function AuthCard({ name, result }) {
  const enabled = result?.data?.enabled;
  const policy = result?.data?.policy;
  const status = result?.status === "failed" ? "Not verified" : enabled ? policy ? policy : "Configured" : "Missing";
  const good = enabled && policy !== "none";
  return <article className="rounded-2xl border border-white/10 bg-slate-900/70 p-4"><div className="flex items-center justify-between gap-3"><p className="font-mono text-sm font-bold">{name}</p>{good ? <CheckCircle2 size={18} className="text-emerald-300" /> : <AlertTriangle size={18} className="text-amber-300" />}</div><p className={`mt-4 text-lg font-bold ${good ? "text-emerald-200" : "text-amber-100"}`}>{status}</p>{result?.data?.selector && <p className="mt-1 text-xs text-slate-500">Selector: {result.data.selector}</p>}{result?.data?.record && <p className="mt-3 line-clamp-2 font-mono text-xs text-slate-500">{result.data.record}</p>}</article>;
}

export default function EmailLab() {
  const [rawEmail, setRawEmail] = useState("");
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  async function investigate() {
    if (rawEmail.trim().length < 10) { setError("Paste a complete email, its headers, or enough message evidence to investigate."); return; }
    setLoading(true); setError(""); setReport(null);
    try {
      const response = await fetch(`${API_URL}/email-lab/investigate`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ raw_email: rawEmail }) });
      const data = await response.json();
      if (!response.ok) throw new Error(data.detail || "The email could not be analyzed.");
      setReport(data);
    } catch (err) { setError(err.message); } finally { setLoading(false); }
  }

  const isRisky = report?.verdict === "HIGH RISK" || report?.verdict === "SUSPICIOUS";
  return <MainLayout hero><main className="min-h-screen bg-slate-950 pb-24 pt-24 text-white"><div className="relative overflow-hidden border-b border-white/10"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_14%_15%,rgba(34,211,238,.18),transparent_28%),radial-gradient(circle_at_85%_60%,rgba(244,63,94,.12),transparent_30%)]" /><div className="relative mx-auto max-w-7xl px-5 py-16 sm:px-8"><p className="inline-flex items-center gap-2 rounded-full border border-cyan-300/20 bg-cyan-300/10 px-3 py-1.5 text-xs font-bold tracking-[.14em] text-cyan-200"><MailCheck size={14} /> EMAIL SECURITY INVESTIGATION LAB</p><h1 className="mt-6 max-w-4xl text-4xl font-bold leading-[1.05] tracking-tight sm:text-6xl">Investigate suspicious email, <span className="bg-gradient-to-r from-cyan-300 to-indigo-300 bg-clip-text text-transparent">without opening it.</span></h1><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-300">Triage headers, sender identity, authentication, URLs and phishing signals. Built around the same investigation flow used with Microsoft Defender, Splunk and VirusTotal—without sending or executing any email content.</p></div></div>
    <div className="mx-auto max-w-7xl px-5 py-14 sm:px-8"><section className="grid gap-7 lg:grid-cols-[1.25fr_.75fr]"><div className="rounded-[2rem] border border-white/10 bg-white/[.04] p-6 sm:p-8"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-cyan-200">Evidence intake</p><h2 className="mt-3 text-3xl font-bold">Paste a suspicious email or headers</h2></div><FileSearch className="text-cyan-200" /></div><p className="mt-3 text-sm leading-6 text-slate-400">Include From, Reply-To, Authentication-Results, Received headers, subject, body, and links when available. Do not paste passwords or confidential content.</p><textarea value={rawEmail} onChange={(event) => setRawEmail(event.target.value)} className="mt-6 min-h-80 w-full rounded-2xl border border-white/10 bg-slate-950 p-4 font-mono text-sm leading-6 text-slate-200 outline-none placeholder:text-slate-600 focus:border-cyan-300/60" placeholder="Paste the original email source or full headers here..." /><div className="mt-4 flex flex-wrap gap-3"><button onClick={investigate} disabled={loading} className="inline-flex items-center gap-2 rounded-xl bg-cyan-300 px-5 py-3 text-sm font-bold text-slate-950 transition hover:bg-cyan-200 disabled:opacity-50">{loading ? <LoaderCircle size={17} className="animate-spin" /> : <ShieldCheck size={17} />}{loading ? "Investigating…" : "Investigate email"}</button><button onClick={() => { setRawEmail(demoEmail); setReport(null); setError(""); }} className="rounded-xl border border-white/15 px-5 py-3 text-sm font-bold text-slate-200 hover:border-cyan-300/50">Load safe demo</button></div>{error && <p className="mt-4 text-sm text-rose-300">{error}</p>}</div>
      <aside className="rounded-[2rem] border border-white/10 bg-gradient-to-br from-indigo-500/15 to-cyan-400/10 p-6 sm:p-8"><p className="text-xs font-bold uppercase tracking-[.14em] text-cyan-200">What Email Lab checks</p><h2 className="mt-3 text-3xl font-bold">From first signal to response.</h2><div className="mt-7 space-y-4">{[["Authentication", "SPF, DKIM and DMARC results plus live posture of the sender domain."], ["Identity", "From, Reply-To and Return-Path mismatches that expose impersonation."], ["IOCs", "URLs, sender addresses and domains extracted into a triage-ready list."], ["Phishing signals", "Urgency, credential/payment lures, URL obfuscation and brand lookalikes."], ["Action plan", "Containment, reporting, blocking and domain-owner remediation steps."]].map(([title, copy]) => <div key={title} className="flex gap-3"><ChevronRight size={17} className="mt-0.5 shrink-0 text-cyan-200" /><div><p className="text-sm font-bold">{title}</p><p className="mt-1 text-sm leading-5 text-slate-400">{copy}</p></div></div>)}</div><p className="mt-8 rounded-xl border border-white/10 bg-slate-950/40 p-4 text-xs leading-5 text-slate-400">Email Lab is for investigation and training. It does not replace your mail gateway, EDR, SIEM, or incident-response process.</p></aside></section>
    {report && <section className="mt-10 space-y-7"><div className={`rounded-[2rem] border p-6 sm:p-8 ${isRisky ? "border-rose-400/30 bg-rose-400/10" : "border-emerald-300/20 bg-emerald-300/10"}`}><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div className="flex items-center gap-4">{isRisky ? <ShieldAlert size={34} className="text-rose-200" /> : <ShieldCheck size={34} className="text-emerald-200" />}<div><p className="text-xs font-bold uppercase tracking-[.14em] text-slate-300">Investigation verdict</p><h2 className="mt-1 text-3xl font-bold">{report.verdict}</h2><p className="mt-1 text-sm text-slate-300">Sender domain: <span className="font-bold text-white">{report.sender_domain || "Not identified"}</span></p></div></div><div className="rounded-2xl border border-white/15 bg-slate-950/30 px-5 py-3 text-center"><p className="text-3xl font-bold">{report.risk_score}<span className="text-base text-slate-400">/100</span></p><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Risk score</p></div></div></div>
      <div className="grid gap-7 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-[2rem] border border-white/10 bg-white/[.04] p-6 sm:p-8"><p className="text-xs font-bold uppercase tracking-[.14em] text-cyan-200">Authentication posture</p><h2 className="mt-3 text-2xl font-bold">Sender-domain email security</h2><div className="mt-6 grid gap-3 sm:grid-cols-3"><AuthCard name="SPF" result={report.authentication.spf} /><AuthCard name="DKIM" result={report.authentication.dkim} /><AuthCard name="DMARC" result={report.authentication.dmarc} /></div></div><div className="rounded-[2rem] border border-white/10 bg-white/[.04] p-6 sm:p-8"><p className="text-xs font-bold uppercase tracking-[.14em] text-cyan-200">Necessary action</p><h2 className="mt-3 text-2xl font-bold">Recommended next steps</h2><ol className="mt-5 space-y-3">{report.recommended_actions.map((action, index) => <li key={action} className="flex gap-3 text-sm leading-6 text-slate-300"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-cyan-300/10 text-xs font-bold text-cyan-200">{index + 1}</span>{action}</li>)}</ol></div></div>
      <div className="grid gap-7 lg:grid-cols-2"><div className="rounded-[2rem] border border-white/10 bg-white/[.04] p-6 sm:p-8"><p className="text-xs font-bold uppercase tracking-[.14em] text-cyan-200">Findings</p><h2 className="mt-3 text-2xl font-bold">Evidence to validate</h2><div className="mt-5 space-y-3">{report.findings.length ? report.findings.map((finding, index) => <article key={`${finding.title}-${index}`} className={`rounded-xl border p-4 ${severity[finding.severity] || severity.low}`}><p className="font-bold">{finding.title}</p><p className="mt-1 text-sm leading-6 opacity-80">{finding.detail}</p></article>) : <p className="rounded-xl border border-white/10 p-4 text-sm text-slate-400">No specific phishing finding was derived from the supplied evidence.</p>}</div></div><div className="rounded-[2rem] border border-white/10 bg-white/[.04] p-6 sm:p-8"><div className="flex items-center gap-2 text-cyan-200"><Link2 size={17} /><p className="text-xs font-bold uppercase tracking-[.14em]">Indicators of compromise</p></div><h2 className="mt-3 text-2xl font-bold">Extracted IOCs</h2><div className="mt-5 space-y-2">{report.indicators.length ? report.indicators.map((ioc, index) => <div key={`${ioc.value}-${index}`} className="rounded-xl border border-white/10 bg-slate-900/70 p-3"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">{ioc.type} · {ioc.severity}</p><p className="mt-1 break-all font-mono text-sm text-slate-200">{ioc.value}</p><p className="mt-1 text-xs text-slate-500">{ioc.note}</p></div><button onClick={() => navigator.clipboard.writeText(ioc.value)} className="rounded-lg p-2 text-slate-400 hover:bg-cyan-300/10 hover:text-cyan-200" title="Copy indicator"><Clipboard size={15} /></button></div></div>) : <p className="rounded-xl border border-white/10 p-4 text-sm text-slate-400">No IOCs were extracted.</p>}</div></div></div>
      <p className="rounded-xl border border-white/10 bg-slate-900/60 p-4 text-xs leading-5 text-slate-400">{report.safety_note}</p></section>}</div></main></MainLayout>;
}
