import { useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { KeyRound, ShieldCheck } from "lucide-react";
import MainLayout from "../layout/MainLayout";

const API_URL = import.meta.env.VITE_API_URL;
const apiError = (payload, fallback) => typeof payload?.detail === "string" ? payload.detail : Array.isArray(payload?.detail) ? payload.detail.map((item) => item.msg).join(" ") : fallback;

export default function ForgotPassword() {
  const navigate = useNavigate();
  const token = new URLSearchParams(useLocation().search).get("token");
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const reset = Boolean(token);
  async function submit(event) { event.preventDefault(); setError(""); setMessage(""); if (reset && password !== confirm) { setError("Passwords do not match."); return; } setBusy(true); try { const response = await fetch(`${API_URL}/auth/password/${reset ? "reset" : "forgot"}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(reset ? { token, password } : { email }) }); const payload = await response.json(); if (!response.ok) throw new Error(apiError(payload, "Unable to complete this request.")); setMessage(payload.message); if (reset) setTimeout(() => navigate("/login"), 1800); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  return <MainLayout><main className="min-h-screen bg-slate-50 px-5 py-12"><div className="mx-auto max-w-md rounded-3xl border border-slate-200 bg-white p-7 shadow-xl sm:p-9"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-slate-950 text-white"><KeyRound size={23} /></div><p className="mt-6 text-sm font-bold uppercase tracking-[.14em] text-slate-400">Account recovery</p><h1 className="mt-2 text-3xl font-bold text-slate-950">{reset ? "Choose a new password" : "Forgot your password?"}</h1><p className="mt-2 text-sm leading-6 text-slate-500">{reset ? "Use a strong password you have not used elsewhere." : "Enter your account email and we will send a reset link if the account exists."}</p><form onSubmit={submit} className="mt-7 space-y-4">{reset ? <><label className="block text-sm font-semibold text-slate-700">New password<input required type="password" minLength="10" value={password} onChange={(event) => setPassword(event.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-3 outline-none focus:border-slate-950" /></label><label className="block text-sm font-semibold text-slate-700">Confirm new password<input required type="password" minLength="10" value={confirm} onChange={(event) => setConfirm(event.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-3 outline-none focus:border-slate-950" /></label><p className="text-xs text-slate-500">At least 10 characters with uppercase, lowercase, and a number.</p></> : <label className="block text-sm font-semibold text-slate-700">Email<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-3 outline-none focus:border-slate-950" /></label>}{error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{message && <p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{message}</p>}<button disabled={busy} className="flex w-full items-center justify-center gap-2 rounded-xl bg-slate-950 px-4 py-3 font-semibold text-white disabled:opacity-60"><ShieldCheck size={17} />{busy ? "Please wait..." : reset ? "Update password" : "Send reset link"}</button></form><button onClick={() => navigate("/login")} className="mt-5 w-full text-sm font-semibold text-slate-600 hover:text-slate-950">Back to sign in</button></div></main></MainLayout>;
}
