import { AlertTriangle, CalendarDays, Globe2, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import MainLayout from "../layout/MainLayout";

const API_URL = import.meta.env.VITE_API_URL;

export default function SharedReport() {
  const { token } = useParams();
  const [report, setReport] = useState(null); const [error, setError] = useState("");
  useEffect(() => { fetch(`${API_URL}/shared/${encodeURIComponent(token)}`).then((response) => response.ok ? response.json() : Promise.reject()).then(setReport).catch(() => setError("This shared report is unavailable or has been removed.")); }, [token]);
  if (error) return <MainLayout><main className="flex min-h-[70vh] items-center justify-center bg-slate-950 px-5 text-center text-white"><div><AlertTriangle className="mx-auto text-amber-300" size={38} /><h1 className="mt-5 text-3xl font-bold">Report unavailable</h1><p className="mt-3 text-slate-400">{error}</p></div></main></MainLayout>;
  if (!report) return <MainLayout><main className="flex min-h-[70vh] items-center justify-center bg-slate-950 text-slate-400">Loading shared report...</main></MainLayout>;
  return <MainLayout hero><main className="min-h-screen bg-slate-950 px-5 pb-24 pt-24 text-white sm:px-8"><div className="mx-auto max-w-5xl"><p className="inline-flex items-center gap-2 rounded-full border border-cyan-300/20 bg-cyan-300/10 px-3 py-1.5 text-xs font-bold tracking-[.14em] text-cyan-200"><ShieldCheck size={14} /> SHARED SENTRYNX REPORT</p><div className="mt-8 grid gap-6 rounded-[2rem] border border-white/10 bg-white/[.05] p-7 sm:grid-cols-[1fr_auto] sm:p-10"><div><div className="flex items-center gap-3 text-slate-400"><Globe2 size={20} /><span className="text-sm font-bold uppercase tracking-wider">Domain intelligence</span></div><h1 className="mt-5 break-all text-4xl font-bold tracking-tight sm:text-5xl">{report.scan_info?.domain}</h1><p className="mt-4 max-w-xl leading-7 text-slate-300">Security posture assessed across infrastructure, web configuration, email authentication, and threat intelligence.</p><p className="mt-6 inline-flex items-center gap-2 text-sm text-slate-400"><CalendarDays size={16} /> {report.scan_info?.scan_time ? new Date(report.scan_info.scan_time).toLocaleString() : "Scan time unavailable"}</p></div><div className="rounded-3xl border border-cyan-300/20 bg-cyan-300/10 p-7 text-center"><p className="text-5xl font-bold text-cyan-200">{report.summary?.overall_score ?? "-"}</p><p className="mt-2 text-xs font-bold uppercase tracking-[.14em] text-cyan-100">{report.summary?.verdict || "Unknown"}</p></div></div><section className="mt-8 grid gap-4 md:grid-cols-2"><article className="rounded-2xl border border-white/10 bg-white/[.04] p-6"><h2 className="font-bold">Key findings</h2><div className="mt-4 space-y-3">{report.issues?.length ? report.issues.map((issue) => <p key={issue} className="border-l-2 border-amber-300 pl-3 text-sm leading-6 text-slate-300">{issue}</p>) : <p className="text-sm text-slate-400">No material scoring deductions were reported.</p>}</div></article><article className="rounded-2xl border border-white/10 bg-white/[.04] p-6"><h2 className="font-bold">Score categories</h2><div className="mt-4 grid grid-cols-2 gap-3">{Object.entries(report.summary?.category_scores || {}).map(([name, score]) => <div key={name} className="rounded-xl bg-slate-900 p-3"><p className="text-xs capitalize text-slate-500">{name.replace("_", " ")}</p><p className="mt-1 text-lg font-bold text-cyan-200">{score}</p></div>)}</div></article></section></div></main></MainLayout>;
}
